export interface WeeklyReportParams {
  startDate: string;
  endDate: string;
  snapshots: Array<{
    date: string;
    keyword: string;
    brand: string;
    provider: string;
    mentionRate: string;
    avgPosition: string | null;
  }>;
  alertCount: number;
}

export function renderWeeklyReport(params: WeeklyReportParams): {
  subject: string;
  html: string;
} {
  const { startDate, endDate, snapshots, alertCount } = params;

  const subject = `[SEO AI Monitor] Weekly Report ${startDate} - ${endDate}`;

  const tableRows =
    snapshots.length === 0
      ? `<tr><td colspan="6" style="padding: 16px; text-align: center; color: #94a3b8;">No monitoring data was collected during this period.</td></tr>`
      : snapshots
          .map(
            (s) => `
      <tr>
        <td style="padding: 8px 12px; border-bottom: 1px solid #e2e8f0;">${s.date}</td>
        <td style="padding: 8px 12px; border-bottom: 1px solid #e2e8f0;">${s.keyword}</td>
        <td style="padding: 8px 12px; border-bottom: 1px solid #e2e8f0;">${s.brand}</td>
        <td style="padding: 8px 12px; border-bottom: 1px solid #e2e8f0;">${s.provider}</td>
        <td style="padding: 8px 12px; border-bottom: 1px solid #e2e8f0;">${s.mentionRate}</td>
        <td style="padding: 8px 12px; border-bottom: 1px solid #e2e8f0;">${s.avgPosition ?? 'N/A'}</td>
      </tr>`,
          )
          .join('\n');

  const html = `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 700px; margin: 0 auto; padding: 20px;">
  <div style="background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 24px;">
    <h2 style="margin: 0 0 8px; color: #0f172a;">Weekly Visibility Report</h2>
    <p style="margin: 0 0 24px; color: #64748b; font-size: 14px;">${startDate} to ${endDate}</p>

    <div style="display: flex; gap: 24px; margin-bottom: 24px;">
      <div style="background: white; border: 1px solid #e2e8f0; border-radius: 6px; padding: 16px; flex: 1;">
        <p style="margin: 0 0 4px; color: #64748b; font-size: 12px;">Total Snapshots</p>
        <p style="margin: 0; font-size: 24px; font-weight: 700; color: #0f172a;">${snapshots.length}</p>
      </div>
      <div style="background: white; border: 1px solid #e2e8f0; border-radius: 6px; padding: 16px; flex: 1;">
        <p style="margin: 0 0 4px; color: #64748b; font-size: 12px;">Alerts Triggered</p>
        <p style="margin: 0; font-size: 24px; font-weight: 700; color: #0f172a;">${alertCount}</p>
      </div>
    </div>

    <table style="width: 100%; border-collapse: collapse; background: white; border: 1px solid #e2e8f0; border-radius: 6px;">
      <thead>
        <tr style="background: #f1f5f9;">
          <th style="padding: 8px 12px; text-align: left; font-size: 12px; color: #64748b; font-weight: 600;">Date</th>
          <th style="padding: 8px 12px; text-align: left; font-size: 12px; color: #64748b; font-weight: 600;">Keyword</th>
          <th style="padding: 8px 12px; text-align: left; font-size: 12px; color: #64748b; font-weight: 600;">Brand</th>
          <th style="padding: 8px 12px; text-align: left; font-size: 12px; color: #64748b; font-weight: 600;">Provider</th>
          <th style="padding: 8px 12px; text-align: left; font-size: 12px; color: #64748b; font-weight: 600;">Mention Rate</th>
          <th style="padding: 8px 12px; text-align: left; font-size: 12px; color: #64748b; font-weight: 600;">Avg Position</th>
        </tr>
      </thead>
      <tbody>
        ${tableRows}
      </tbody>
    </table>
  </div>
  <p style="color: #94a3b8; font-size: 12px; margin-top: 16px; text-align: center;">Generated by SEO AI Monitor</p>
</body>
</html>`.trim();

  return { subject, html };
}
